name: 'pre-Release Changelog Update'

on:
  workflow_call:
  release:
    types: [prereleased]

permissions:
  contents: write
  pull-requests: write

jobs:
  call-workflow-update-changelog:
    uses: figuren-theater/.github/.github/workflows/prerelease-changelog-update.yml@main
    secrets:
      BOT_TOKEN: ${{ secrets.USED_AS_BOT_TOKEN }}

